---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: tete-local
type: Opaque
data:
  connection-string: U2VydmVyPXRldGUtZGItc3ZjOyBEYXRhYmFzZT1UZXRlOyBVc2VyIElkPXNhOyBQYXNzd29yZD10ZXN0UGFzc3dvcmRcITs=
  password: dGVzdFBhc3N3b3JkIQ== #testPassword!

---
apiVersion: v1
kind: Secret
metadata:
  name: cert-credentials
  namespace: tete-local
type: Opaque
data:
  cert-password: dGV0ZVBhc3N3b3JkIQo= #tetePassword!
